// Copyright 2017-2021 @cennznet/extension-base authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@cennznet/extension-base', version: '0.38.3' };
