// Copyright 2017-2021 @cennznet/extension-dapp authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@cennznet/extension-dapp', version: '0.38.2' };
